tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "bat"
brew "exa"
brew "git", link: false
brew "httpie"
brew "nvm"
cask "alfred"
cask "gitkraken"
cask "google-chrome"
cask "visual-studio-code"
